### ISSUE TITLE
Failed to update voice list on start (TTS)

### ISSUE THREAD

**Issue by stackia** [hugobloem/homeassistant-addons#37]
I cannot update the voice list on start. Got the following errors:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service microsoft: starting
s6-rc: info: service microsoft successfully started
s6-rc: info: service discovery: starting
ERROR:wyoming_microsoft_tts.download:Failed to update voices list
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_microsoft_tts/download.py", line 77, in get_voices
    json.dump(transform_voices_files(response), download_file, indent=4)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_microsoft_tts/download.py", line 46, in transform_voices_files
    "region": country.alpha_2,
AttributeError: 'NoneType' object has no attribute 'alpha_2'
ERROR:wyoming_microsoft_tts.download:Failed to load /data/voices.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_microsoft_tts/download.py", line 86, in get_voices
    return json.load(voices_file)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:__main__:Ready
[16:10:39] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

And here is the API response of `https://eastasia.tts.speech.microsoft.com/cognitiveservices/voices/list`:

https://gist.githubusercontent.com/stackia/d9d1f0d02e2982edd472557a5ed5defc/raw/708f14cc54052d3ab851bbfc73aad4f040940bc5/voice_list.json

**Comment by hugobloem** [comment]
Apologies for the delay, I have been very busy.

This should be fixed in 1.0.7.
